# Generated by Django 6.0.4 on 2026-05-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_duration_months_booking_emergency_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdocument',
            name='document_type',
            field=models.CharField(choices=[('aadhaar', 'Aadhaar / PAN Card'), ('college_id', 'College ID'), ('company_id', 'Company ID'), ('passport_photo', 'Passport Photo'), ('address_proof', 'Address Proof')], max_length=20),
        ),
    ]
