# Generated by Django 5.2.5 on 2026-05-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0003_visitorrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorrequest',
            name='requested_check_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
