# Generated by Django 5.2.5 on 2026-05-13 13:55

import properties.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_inquiry_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='alternate_contact',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='property',
            name='custom_amenities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='property',
            name='drinking_rules',
            field=models.CharField(blank=True, default='No public-area drinking', max_length=160),
        ),
        migrations.AddField(
            model_name='property',
            name='gate_closing_time',
            field=models.CharField(blank=True, default='11:00 PM', max_length=60),
        ),
        migrations.AddField(
            model_name='property',
            name='google_maps_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='property',
            name='lifestyle_highlights',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='property',
            name='nearby_colleges',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='property',
            name='nearby_landmarks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='property',
            name='nearby_places',
            field=models.JSONField(blank=True, default=properties.models.default_nearby_places),
        ),
        migrations.AddField(
            model_name='property',
            name='nearby_transit',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='property',
            name='overview_custom_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='property',
            name='pricing_food_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='pricing_maintenance_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='pricing_monthly_rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='pricing_security_deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='quiet_hours',
            field=models.CharField(blank=True, default='10:30 PM to 6:30 AM', max_length=120),
        ),
        migrations.AddField(
            model_name='property',
            name='smoking_policy',
            field=models.CharField(blank=True, default='Not allowed indoors', max_length=120),
        ),
        migrations.AddField(
            model_name='property',
            name='suitable_for',
            field=models.CharField(blank=True, default='students_and_professionals', max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='videos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='property',
            name='visitor_rules',
            field=models.CharField(blank=True, default='Day visitors till 8:00 PM', max_length=160),
        ),
        migrations.AddField(
            model_name='property',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='review',
            name='is_verified_resident',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='stay_duration',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
