# Generated by Django 5.2.5 on 2026-04-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_invoice_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='paid_at',
            new_name='payment_date',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=20),
        ),
    ]
