# Generated by Django 5.2.5 on 2026-05-17 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_rename_paid_at_invoice_payment_date_and_more'),
        ('properties', '0005_property_alternate_contact_property_custom_amenities_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='food_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='maintenance_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('upi', 'UPI'), ('gpay', 'Google Pay'), ('phonepe', 'PhonePe'), ('paytm', 'Paytm'), ('bhim', 'BHIM UPI'), ('bank_transfer', 'Bank Transfer'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('pending_verification', 'Pending Verification'), ('paid', 'Paid'), ('failed', 'Failed'), ('rejected', 'Rejected')], default='unpaid', max_length=24),
        ),
        migrations.CreateModel(
            name='PaymentSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_type', models.CharField(choices=[('rent', 'Rent'), ('deposit', 'Security Deposit')], default='rent', max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_id', models.CharField(max_length=100)),
                ('payment_method', models.CharField(choices=[('upi', 'UPI'), ('gpay', 'Google Pay'), ('phonepe', 'PhonePe'), ('paytm', 'Paytm'), ('bhim', 'BHIM UPI'), ('bank_transfer', 'Bank Transfer'), ('other', 'Other')], default='upi', max_length=20)),
                ('screenshot', models.ImageField(upload_to='payment_proofs/%Y/%m/')),
                ('status', models.CharField(choices=[('pending_verification', 'Pending Verification'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='pending_verification', max_length=24)),
                ('owner_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='payments.invoice')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_submissions', to='properties.property')),
                ('resident', models.ForeignKey(limit_choices_to={'role': 'resident'}, on_delete=django.db.models.deletion.CASCADE, related_name='payment_submissions', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payment_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyPaymentSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upi_id', models.CharField(blank=True, max_length=120)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='payment_qr/%Y/%m/')),
                ('account_holder_name', models.CharField(blank=True, max_length=150)),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('payment_instructions', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_settings', to='properties.property')),
            ],
        ),
    ]
